### ISSUE TITLE
Notes and Road map

### ISSUE THREAD

**Issue by h-a-graham** [h-a-graham/gblidar#4]
The API for England has now been updated. It's time to improve this package. 

potrals for inspecting API access:
English Portal: https://environment.data.gov.uk/survey
Scottish Portal: https://remotesensingdata.gov.scot/data#/map
Welsh Portal: https://datamap.gov.wales/maps/lidar-viewer/view#/

Roadmap: 

- [x] fix english lidar search for new API.
- [x] Add fast functions to access the data hosted as WCS (composites)
- [ ] Add search for Scottish Data
- [ ] Add search for Welsh Data.

**Comment by h-a-graham** [comment]
What are these data and should we add them: 
https://environment.data.gov.uk/dataset/e1b35f18-35cc-420d-be54-1467fa5d1519

https://environment.data.gov.uk/dataset/ce8fe7e7-bed0-4889-8825-19b042e128d2  ( this one I think is pointless now we have the WCS we can just warp at a lower res)
